### ISSUE TITLE
Gem is not released

### ISSUE THREAD

**Issue by mrbrdo** [spree/spree_api_v1#1]
@rafalcymerys the Readme says to put it in Gemfile, but the gem is not released on rubygems.org, at least not as `spree_api_v1`.

**Comment by mrbrdo** [comment]
@rafalcymerys so could you guys release the gem?

**Comment by damianlegawiec** [comment]
Hey @mrbrdo 

I see the gem was released and is available on Rubygems - https://rubygems.org/gems/spree_api_v1
